version: '3.8'

services:
  my_rust_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    volumes:
      - .:/app
    command: ["./group-generator"]

